
{{- range $name, $svc := .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: {{ $svc.image }}
          ports:
            - containerPort: {{ $svc.containerPort | default $svc.port }}
          env:
            - name: PORT
              value: "{{ $svc.port }}"

            {{- if $svc.productCatalogServiceAddr }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ $svc.productCatalogServiceAddr }}"
            {{- end }}

            # Profiler env var
            {{- if $svc.profiler.enabled }}
            - name: GOOGLE_CLOUD_PROJECT
              value: "{{ $svc.profiler.projectId }}"
            {{- else }}
            - name: GOOGLE_CLOUD_PROFILER_DISABLE
              value: "1"
            {{- end }}

          {{- if $svc.livenessProbe }}
          livenessProbe:
            {{- toYaml $svc.livenessProbe | nindent 12 }}
          {{- end }}

          {{- if $svc.readinessProbe }}
          readinessProbe:
            {{- toYaml $svc.readinessProbe | nindent 12 }}
          {{- end }}

          {{- if $svc.resources }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          {{- end }}
---
{{- end }}

