

{{- range $name, $svc := .Values.microservices }}
{{- if $svc.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-{{ $svc.name }}
  minReplicas: {{ $svc.hpa.minReplicas | default 1 }}
  maxReplicas: {{ $svc.hpa.maxReplicas | default 3 }}
  metrics:
  {{- range $svc.hpa.metrics }}
    - type: {{ .type }}
      {{- if eq .type "Resource" }}
      resource:
        name: {{ .resource.name }}
        target:
          type: {{ .resource.target.type }}
          averageUtilization: {{ .resource.target.averageUtilization }}
      {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}

