

{{- range $name, $svc := .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.containerPort | default $svc.port }}
      protocol: TCP
---
{{- end }}

